[Service]
Environment=DISABLED_SOURCES=4khdhub,cinehdplus,cuevana,einschalten,eurostreaming,frembed,frenchcloud,hdhub4u,homecine,kinoger,kokoshka,megakino,meinecloud,mostraguarda,movix,rgshows,streamkiste,verhdlink,vidsrc,vixsrc
